config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show, :edit, :update]
  root 'movies#index'
  resources :movies do
    resources:comments, :only => [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :movie
  has_many :comments
end

app/models/post_image.rb
class PostImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_movie
  before_action :check_login, only: [:destroy]
  
  def create
    @comment = @movie.comments.create! comments_params
    @comment.update(:score => params[:score])
    redirect_to @movie
  end 
  
  def destroy
    @movie.comments.destroy params[:id]
    redirect_to @movie
  end 
  
  private
  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
  
  def check_login
    redirect_to :root if current_user == nil || @movie.comments.find(params[:id]).user_id != current_user.id
  end 
  
  def comments_params
    params.required(:comment).permit(:content)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :check_login, only: [ :new, :edit, :create, :update, :destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end
    
    def check_login
      redirect_to :root if current_user == nil || @movie.user_id != current_user.id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_login, only: [:edit, :update]
  
  def show
  end 
  
  def edit
  end 
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User name was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
  private
  def set_user
    @user = User.find(params[:id])
  end 
  
  def check_login
    redirect_to :root if current_user == nil || @user.id != current_user.id
  end
  
  def user_params
    params.required(:user).permit(:name)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><%= tag.div('', class: 'score', data: {score: comment.score}) %></p>

    <p>内容:<%= comment.content%></p>
    <p>評価 :<%= comment.score%>点</p>
    <div id="score<%= comment.id%>"></div>    
    <script>
      $('#score<%= comment.id%>').raty({
        size      : 36,
        starOff   : '<%= asset_path('star-off.png') %>',
        starOn    : '<%= asset_path('star-on.png') %>',
        half      : false,
        readOnly: true,
        score: <%= comment.score %>,
      });
    </script>
    <% if user_signed_in? && comment.user_id == current_user.id %>
      <p><%= link_to "Delete", [@movie, comment], method: :delete, data: {confirm: 'Are you sure?' } %></p>
    <% end %>

app/views/comments/_new.html.erb
<%= form_with(model: [@movie, Comment.new], remote: true) do |form| %>
<div class="movie_rate"></div>
Your Comment:<br>
<%= form.text_field :content, id: :movie_comments %>
<%= form.submit %>
<% end %>

  <!-- 評価javascript -->
  <script>
  $('#movie_rate').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',

    scoreName: 'comment[score]',
    half: false,
  });
  </script> 

app/views/layouts/_footer.html.erb
  <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>動画投稿SNSサイト</p>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Rails Tube", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to 'Movies', movies_path, class: "dropdown-item" %>
      <% if user_signed_in? %>
        <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
        <%= link_to 'Sign Out', destroy_user_session_path, class: "dropdown-item", method: :delete %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "dropdown-item" %>
        <%= link_to 'Sign In', new_user_session_path, class: "dropdown-item" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  
  <div class="field">
    <%= form.label :movie %>
    <%= form.file_field :movie %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if user_signed_in? && movie.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Movie', new_movie_path %>
<% end %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @movie.content %>
</p>

<p>
  <strong>movies:</strong>
  <% if @movie.movie.attached? %>
    <% video_tag rails_blob_path(@movie.movie, disposition: "attachment"), :controls => true %>
  <% end %>
</p>

<h2>Comments</h2>
<div id="comments">
  <%= render @movie.comments %>
</div>

<% if user_signed_in? %>
  <%= render 'comments/new', movie: @movie %>
<% end %>

<% if user_signed_in? && @movie.user_id == current_user.id %>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
<% end %>

<%= link_to 'Back', movies_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this post from being saved:</h2>

       <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

   <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %> 

app/views/users/show.html.erb
<%= @user.name %>

 <% if current_user.id == @user.id %>
<%= link_to 'Edit Name', edit_user_path(@user) %>
<% end %> 